remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Edison Martínez Osorio
submodulo: Lógica de programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/proyecto-edison.appspot.com/o/IMG-20210111-WA0003.jpg?alt=media&token=e65cfede-1090-4f8c-b08a-161b7d6cb77c

